[package]
name = "bindings"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
alloy = { workspace = true }

[lints]
workspace = true
