[package]
name = "taiko_preconf_avs_node"
version = "0.2.25"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { version = "0.13", features = [
    "full",
    "node-bindings",
    "rlp",
    "rpc-types-beacon",
    "rpc-types",
] }
alloy-rlp = "0.3"
tokio = { version = "1.38", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
jsonrpsee = { version = "0.24", features = ["http-client", "server"] }
jsonwebtoken = "9.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
anyhow = "1.0.86"
k256 = { version = "0.13", features = ["ecdsa"] }
ecdsa = "0.16"
elliptic-curve = "0.13"
reqwest = "0.12"
hex = "0.4"
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "ethereum-consensus", rev = "ade5ce6c4a19107c1059e5338d8f18855bd2d931" }
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "beacon-api-client", rev = "ade5ce6c4a19107c1059e5338d8f18855bd2d931" }
dotenv = "0.15"
chrono = "0.4"
futures-util = "0.3"
http = "1.2"
flate2 = "1.1"
alloy-json-rpc = "0.13"

[dev-dependencies]
mockall_double = "0.3"
mockall = "0.13"
mockito = "1.4"

[features]
default = ["extra_gas_percentage"]
use_mock = []
extra_gas_percentage = []
