[package]
name = "taiko_preconf_avs_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { version = "0.1", features = ["full", "node-bindings"] }
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
jsonrpsee = { version = "0.24", features = ["http-client", "server"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
anyhow = "1.0.86"
k256 = "0.13"
elliptic-curve = "0.13"
reqwest = "0.12"
hex = "0.4"
tiny-keccak = "2.0"
secp256k1 = "0.29"
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "beacon-api-client" }
dotenv = "0.15"
libp2p =  { version = "0.54.0", features = ["full", "tcp", "dns", "websocket", "tokio", "identify", "yamux", "noise", "gossipsub"] }
discv5 = { version = "0.6.0", features = ["libp2p"] }
futures =  "0.3.25"
log = "0.4.17"
serde_millis = "0.1.1"
libp2p-mplex = "0.41"
void = "1.0.2"
bincode = "1.3"
serde_bytes = "0.11"

[dev-dependencies]
mockito = "1.4"
