[package]
name = "taiko_preconf_avs_node"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy = { version = "0.12", features = [
    "full",
    "node-bindings",
    "rlp",
    "rpc-types-beacon",
    "rpc-types",
] }
alloy-rlp = "0.3"
tokio = { version = "1.38", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
jsonrpsee = { version = "0.24", features = ["http-client", "server"] }
jsonwebtoken = "9.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
anyhow = "1.0.86"
k256 = { version = "0.13", features = ["ecdsa"] }
ecdsa = "0.16"
elliptic-curve = "0.13"
reqwest = "0.12"
hex = "0.4"
beacon-api-client = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "beacon-api-client" }
ethereum-consensus = { git = "https://github.com/ralexstokes/ethereum-consensus", package = "ethereum-consensus" }
ssz_rs = { git = "https://github.com/ralexstokes/ssz-rs", rev = "84ef2b71aa004f6767420badb42c902ad56b8b72" }
dotenv = "0.15"
rand_core = "0.6"
chrono = "0.4"
futures-util = "0.3"
http = "1.2"
flate2 = "1.1"

[dev-dependencies]
mockall_double = "0.3"
mockall = "0.13"
mockito = "1.4"
alloy-json-rpc = "0.12"

[features]
default = ["extra_gas_percentage"]
use_mock = []
extra_gas_percentage = []

# TODO: remove when the bug is fixed (https://github.com/ralexstokes/ssz-rs/issues/163)
[patch."https://github.com/ralexstokes/ssz-rs"]
ssz_rs = { git = "https://github.com/noahfigueras/ssz-rs", branch = "partial_merkle_tree" }
