services:

  bootnode:
    image: bootnodep2p
    container_name: bootnode
    networks:
      p2p_network:
        ipv4_address: 172.16.1.101
    command: ["p2p-boot-node", "172.16.1.101", "9000"]
        
  node1:
    image: nodep2p
    depends_on:
      - bootnode
    container_name: node1
    environment:
      - BOOT_NODE_IP=172.16.1.101
      - ADDRESS=172.16.1.201
      - SEND_PREFIX=node1
    networks:
      p2p_network:
        ipv4_address: 172.16.1.201

  node2:
    image: nodep2p
    depends_on:
      - bootnode
    container_name: node2
    environment:
      - BOOT_NODE_IP=172.16.1.101
      - ADDRESS=172.16.1.202
      - SEND_PREFIX=node2
    networks:
      p2p_network:
        ipv4_address: 172.16.1.202

  node3:
    image: nodep2p
    depends_on:
      - bootnode
    container_name: node3
    environment:
      - BOOT_NODE_IP=172.16.1.101
      - ADDRESS=172.16.1.203
      - SEND_PREFIX=node3
    networks:
      p2p_network:
        ipv4_address: 172.16.1.203

networks:
  p2p_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  shared_volume:
