name: "[Nethermind] Taiko Preconf AVS Stack - Pytest"

on:
    workflow_dispatch:
    push:
      branches: [master]

env:
  TARGET_MACHINE_IP: 178.79.141.170
jobs:
  build:
    name: Set and run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.TARGET_MACHINE_IP }} >> ~/.ssh/known_hosts

      - name: SSH into target machine
        run: |
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=30 root@${{ env.TARGET_MACHINE_IP }} << 'EOF'
            docker pull nethswitchboard/taiko-protocol-dev:latest
            docker pull nethswitchboard/taiko-client-dev:latest

            kurtosis enclave rm taiko-preconf-devnet --force
            kurtosis clean -a
            cd ~/preconfirm-devnet-package
            git pull
            kurtosis run --enclave taiko-preconf-devnet . --args-file network_params.yaml

            cd ~/Taiko-Preconf-AVS/e2e_tests
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest
          EOF

      - name: Summary
        run: |
          echo "## Pytest completed :green_circle:" >> $GITHUB_STEP_SUMMARY
