name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Build
      run: cargo build -p taiko_preconf_avs_node --verbose
    - name: Run tests
      run: cargo test -p taiko_preconf_avs_node --verbose
    - name: Run tests with use_mock feature
      run: cargo test -p taiko_preconf_avs_node --features use_mock --verbose
